### ISSUE TITLE
[0.8] Release TODO

### ISSUE THREAD

**Issue by ignasbernotas** [mysteriumnetwork/mysterium-vpn#468]
[0.8 Release]
- [x] Test and register bugs: @Germuxas (https://github.com/mysteriumnetwork/product/issues/423)
  - [x] Windows 7
  - [ ] Windows 8
  - [ ] Windows 10
  - [ ] OSX (low priority)
- [x] Add active user count to SP page: @Waldz (https://github.com/mysteriumnetwork/mysterium-vpn/issues/451)
- [x] ETH Wallet address: @donce (https://github.com/mysteriumnetwork/mysterium-vpn/issues/458)
- [x] Update T&C: @ignasbernotas (https://github.com/mysteriumnetwork/product/issues/422)

**Comment by ignasbernotas** [comment]
- [ ] Test and register bugs: @Germuxas:
  - [ ] Windows 7
  - [ ] Windows 8
  - [ ] Windows 10
  - [ ] OSX (low priority)
- [ ] Add active user count to SP page: @Waldz 
- [ ] ETH Wallet address: @donce 
- [ ] NAT manual configuration instructions @zolia 
- [ ] Error message with NAT instructions link when NAT fails: @zolia
