### ISSUE TITLE
[Dual node] - Week 14/15 TODO

### ISSUE THREAD

**Issue by ignasbernotas** [mysteriumnetwork/mysterium-vpn#478]
- [ ] NAT manual configuration instructions: @zolia (https://github.com/mysteriumnetwork/docs/issues/22)
- [ ] Error message with NAT instructions link when NAT fails: @zolia (https://github.com/mysteriumnetwork/node/issues/794)
- [ ] Stop VPN connection: https://github.com/mysteriumnetwork/node/issues/822

**Comment by mjankauskas** [comment]
What about whitelist and data center IP detection/categorization
?
